blank_issues_enabled: false
contact_links:
    - name: Ask a Question (on Discord)
      url: https://discord.com/
      about: Please ask and answer questions for NomNom here (actual invite link will be added later).
