name: Generate Badges

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  generate-badges-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Previous Badge Cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: badges-downloads-${{ hashFiles('.github/workflows/scripts/generate_badges_downloads.py') }}
          restore-keys: |
            badges-downloads-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: pip install numerize requests

      # script creates directory gh-pages/badges/downloads
      - name: Generate Badges
        run: python .github/workflows/scripts/generate_badges_downloads.py

      - name: Detect Changes in Badge Files
        run: |
          mkdir -p .cache
          skip=true
          for file in gh-pages/badges/downloads/*.json; do
            filename=$(basename "$file")
            if [ -f ".cache/$filename" ]; then
              if cmp -s ".cache/$filename" "$file"; then
                echo "$filename: No change."
              else
                echo "$filename: Changed."
                skip=false
              fi
            else
              echo "$filename: No cache found. Will deploy."
              skip=false
            fi
          done
          echo "skip_deploy=$( $skip )" >> $GITHUB_ENV

      - name: Update Cache
        if: env.skip_deploy != 'true'
        run: |
          mkdir -p .cache
          cp gh-pages/badges/downloads/*.json .cache/

      - name: Upload Artifact
        if: env.skip_deploy != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-badges-downloads
          path: gh-pages/badges/

  generate-badges-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # script creates directory gh-pages/badges/test
      - name: Generate Badges
        run: python .github/workflows/scripts/generate_badges_test.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-badges-test
          path: gh-pages/badges/

  deploy:
    needs: [generate-badges-downloads, generate-badges-test]
    uses: ./.github/workflows/deploy-pages.yml
    with:
      identifier: "badges"
