name: Generate Badges

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  generate-badges-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: pip install numerize requests

      # script creates directory gh-pages/badges/downloads
      - name: Generate Badges
        run: python .github/workflows/scripts/generate_badges_downloads.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-badges-downloads
          path: gh-pages/badges/

  # Example job for generating a second set of badges. Do not forget to add to "needs" of the actual deploy job below.
  # generate-badges-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'

  #     # script creates directory gh-pages/badges/test
  #     - name: Generate Badges
  #       run: python .github/workflows/scripts/generate_badges_test.py

  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: gh-pages-badges-test
  #         path: gh-pages/badges/

  deploy-pages:
    needs: [generate-badges-downloads]
    uses: ./.github/workflows/deploy-pages.yml
    with:
      identifier: "badges"
