# jobs:
#   # Deployment job
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build

#     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
#     permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment originates from an appropriate source

#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4


name: Deploy Pages

on:
  workflow_call:
  # workflow_run:
  #   workflows:
  #     - Build Site Dummy
  #     - Generate Badges
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Previous WASM Cache
        id: cache-restore-wasm
        uses: actions/cache/restore@v4
        with:
          # fail-on-cache-miss: true
          path: site/html/
          key: wasm-${{ hashFiles('.github/workflows/dummy.yml') }}
          restore-keys: |
            wasm-

      - name: Restore Previous Badge Cache
        id: cache-restore-badges
        uses: actions/cache/restore@v4
        with:
          # fail-on-cache-miss: true
          lookup-only: true
          path: site/badges/
          key: badges-downloads-${{ hashFiles('.github/workflows/scripts/generate_badges_downloads.py') }}
          restore-keys: |
            badges-downloads-

      - name: Validate folder presence
        run: |
          missing=false

          if [ ! -d "site/html" ]; then
            echo "❌ site/html is missing"
            missing=true
          fi

          if [ ! -d "site/badges" ]; then
            echo "❌ site/badges is missing"
            missing=true
          fi

          if [ "$missing" = true ]; then
            exit 1
          else
            echo "✅ Both folders are present"
          fi

      # - name: Download (Content)
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: pages-content
      #     path: site/html/

      # - name: Download (Badges)
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: pages-badges
      #     path: site/badges/

      # - name: Merge and Prepare Pages
      #   run: |
      #     mkdir site
      #     cp -r site/html/* site/
      #     cp -r site/badges/* site/

      - name: Setup Pages
        # if: steps.cache-restore-wasm.outputs.cache-hit == 'true' && steps.cache-restore-badges.outputs.cache-hit == 'true'
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        # if: steps.cache-restore-wasm.outputs.cache-hit == 'true' && steps.cache-restore-badges.outputs.cache-hit == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        # if: steps.cache-restore-wasm.outputs.cache-hit == 'true' && steps.cache-restore-badges.outputs.cache-hit == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
