name: Deploy Pages

on:
  workflow_call:
    inputs:
      identifier:
        required: true
        type: string

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: gh-pages-${{ inputs.identifier }}*  # not -* as releases do not have a suffix
          merge-multiple: true
          path: ${{ inputs.identifier }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.identifier }}
          destination_dir: ${{ inputs.identifier }}
